name: nonaka_shop
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  google_fonts: ^4.0.1
  dio: ^4.0.6

dev_dependencies:
  build_runner:
  mobx_codegen: ^2.1.1
  modular_test: ^2.0.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
